DROP TABLE IF EXISTS ESTUDIANTE;
CREATE TABLE ESTUDIANTE (
id INTEGER auto_increment NOT NULL PRIMARY KEY,
nombre VARCHAR(40) NOT NULL,
apellido VARCHAR(40) NOT NULL,
email VARCHAR(40) NOT NULL,
creditos INTEGER NOT NULL,
semestre INTEGER NOT NULL,
promedio INTEGER NOT NULL
);

ALTER TABLE ESTUDIANTE ADD CONSTRAINT UNQ_ESTUDIANTE_EMAIL UNIQUE(email)