--DROP TABLE EVAL_TIP_GESTION CASCADE CONSTRAINTS;
--DROP TABLE EVAL_REQ_DETALLE;
--DROP SEQUENCE EVAL_REQ_DETALLE_SEQ;

--ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
--ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD/MM/YYYY HH24:MI:SS';


CREATE TABLE EVAL_TIP_GESTION 
(
N_ID_TIPO_GESTION NUMBER(1) PRIMARY KEY NOT NULL,
C_DESCRIPCION VARCHAR2(30) NOT NULL,
N_PESO NUMBER(2) NOT NULL,
N_ESTADO VARCHAR2(1) NOT NULL,
C_USU_REGISTRO VARCHAR2(6) NOT NULL,
D_FEC_REGISTRO TIMESTAMP NOT NULL
);


CREATE TABLE EVAL_REQ_DETALLE 
(
N_ID_REQ_DETALLE NUMBER(4) PRIMARY KEY NOT NULL,
N_ID_RQ NUMBER(7) NOT NULL,
C_COD_AUTORIZACION VARCHAR2(6) NOT NULL,
D_FEC_TRX DATE NOT NULL,
N_MTO NUMBER(7,3) NOT NULL,
C_USU_REGISTRO VARCHAR2(7) NOT NULL,
D_FEC_REGISTRO TIMESTAMP NOT NULL,
N_ID_TIPO_GESTION NUMBER(1) NULL,
D_FEC_GESTION TIMESTAMP NULL,

CONSTRAINT EVAL_REQ_DETALLE_N_ID_TIPO_GESTION_FK 
   FOREIGN KEY (N_ID_TIPO_GESTION)
   REFERENCES EVAL_TIP_GESTION(N_ID_TIPO_GESTION) ON DELETE CASCADE
);


CREATE SEQUENCE EVAL_REQ_DETALLE_SEQ
   START WITH 1000
   INCREMENT BY 1
   MAXVALUE 10000
   NOCACHE
   NOCYCLE;



INSERT INTO EVAL_TIP_GESTION VALUES(3, 'Gestion Visa', 60, '1', 'GNOAIN', CURRENT_TIMESTAMP);
INSERT INTO EVAL_TIP_GESTION VALUES(4, 'Gestion MC', 50, '1', 'GNOAIN', CURRENT_TIMESTAMP);
INSERT INTO EVAL_TIP_GESTION VALUES(5, 'Contracargo Visa', 0, '1', 'GNOAIN', CURRENT_TIMESTAMP);
INSERT INTO EVAL_TIP_GESTION VALUES(6, 'Contracargo MC', 0, '1', 'GNOAIN', CURRENT_TIMESTAMP);


INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793862, '080342', CURRENT_DATE, 14.900, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793866, '000838', CURRENT_DATE, 14.900, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793890, 'T05657', CURRENT_DATE, 15.010, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793890, 'T02270', CURRENT_DATE, 27.810, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793890, 'T06869', CURRENT_DATE, 30.900, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793890, 'T06010', CURRENT_DATE, 31.760, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793842, 'T05540', CURRENT_DATE, 35.500, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793842, 'T07955', CURRENT_DATE, 36.900, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793901, '046177', CURRENT_DATE, 37.900, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793898, '007072', CURRENT_DATE, 42.850, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793873, 'T07128', CURRENT_DATE, 113.850, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793849, '028185', CURRENT_DATE, 178.200, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793891, 'T00330', CURRENT_DATE, 619.000, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO EVAL_REQ_DETALLE VALUES(EVAL_REQ_DETALLE_SEQ.NEXTVAL, 2793878, '079822', CURRENT_DATE, 1856.960, 'SISTEMA', CURRENT_TIMESTAMP, NULL, NULL);

COMMIT;

   
SELECT * FROM EVAL_TIP_GESTION;
SELECT * FROM EVAL_REQ_DETALLE;


-- Create package and procedure

CREATE OR REPLACE PACKAGE PKG_EVAL_ASIGNACION AS
   PROCEDURE PR_ASIG_TIP_GESTION;
END PKG_EVAL_ASIGNACION;


CREATE OR REPLACE PACKAGE BODY PKG_EVAL_ASIGNACION AS
 PROCEDURE PR_ASIG_TIP_GESTION IS
     CURSOR c_req_detalle IS
     SELECT * FROM EVAL_REQ_DETALLE;  
     
     req_detalle_rec c_req_detalle%ROWTYPE;
 BEGIN    
 
   OPEN c_req_detalle;
   LOOP
      FETCH c_req_detalle INTO req_detalle_rec;
      EXIT WHEN c_req_detalle%notfound;
      
      IF req_detalle_rec.n_mto <= 10 THEN
      
        UPDATE EVAL_REQ_DETALLE 
        SET N_ID_TIPO_GESTION = '6', D_FEC_GESTION = CURRENT_TIMESTAMP 
        WHERE N_ID_REQ_DETALLE = req_detalle_rec.n_id_req_detalle;
        
      ELSIF req_detalle_rec.n_mto > 10 AND req_detalle_rec.n_mto <= 35 THEN
      
        UPDATE EVAL_REQ_DETALLE 
        SET N_ID_TIPO_GESTION = '5', D_FEC_GESTION = CURRENT_TIMESTAMP 
        WHERE N_ID_REQ_DETALLE = req_detalle_rec.n_id_req_detalle;
        
      ELSIF req_detalle_rec.n_mto > 35 AND req_detalle_rec.n_mto <= 100 THEN
      
        UPDATE EVAL_REQ_DETALLE 
        SET N_ID_TIPO_GESTION = '4', D_FEC_GESTION = CURRENT_TIMESTAMP 
        WHERE N_ID_REQ_DETALLE = req_detalle_rec.n_id_req_detalle;
        
      ELSIF req_detalle_rec.n_mto > 100 THEN
      
        UPDATE EVAL_REQ_DETALLE 
        SET N_ID_TIPO_GESTION = '3', D_FEC_GESTION = CURRENT_TIMESTAMP 
        WHERE N_ID_REQ_DETALLE = req_detalle_rec.n_id_req_detalle;
      END IF;
      
    END LOOP;
    
    COMMIT;
   CLOSE c_req_detalle;
    
 END;
END PKG_EVAL_ASIGNACION;


-- Call
BEGIN
  PKG_EVAL_ASIGNACION.PR_ASIG_TIP_GESTION;
END;

SELECT * FROM EVAL_REQ_DETALLE;




